include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_declarations: true

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gr.dart'
    - '**/generated_plugin_registrant.dart'
  plugins:
    - custom_lint