name: skywatch
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  json_serializable: ^6.7.1
  http: ^1.1.0
  flutter_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  gap: ^3.0.1
  auto_route: ^7.8.4
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  sliver_tools: ^0.2.12
  fuzzywuzzy: ^1.1.6
  permission_handler: ^11.0.1
  lottie: ^2.7.0
  timeago: ^3.6.0
  hooks_riverpod: ^2.4.5
  flutter_hooks: ^0.20.3
  image_picker: ^1.0.4
  video_player: ^2.8.1
  json_annotation: ^4.8.1
  shimmer: ^3.0.0
  flutter_localizations:
    sdk: flutter
  iso_countries: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  riverpod_generator: ^2.3.5
  custom_lint: ^0.5.6
  riverpod_lint: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^7.3.2
  flutter_gen_runner: ^5.3.2
  flutter_native_splash: ^2.3.5
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/lottie/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_48.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#1A1D1E"
    theme_color: "#4B87C5"
  windows:
    generate: true
    icon_size: 48
  macos:
    generate: true

flutter_gen:
  output: lib/presentation/components
  integrations:
    flutter_svg: false

flutter_intl:
  enabled: true
  arb_dir: lib/presentation/l10n/arb
  output_dir: lib/presentation/l10n
  class_name: Localization
  main_locale: en_US
  localizely:
    project_id: f10bf105-5562-43c3-bde5-d6f4b7138b70
